name: EZVIZ Snapshot Grabber
version: 1.0.1
slug: ezviz_snapshots
description: Obtiene snapshots de c√°maras EZVIZ y los guarda en www/snapshots
arch:
  - aarch64
startup: once
boot: manual
host_network: false

options:
  app_key: ""
  app_secret: ""
  token: ""
  camaras:
    - name: ""
      serial: ""

schema:
  app_key: str
  app_secret: str
  token: str
  camaras:
    - name: str
      serial: str
