name: EZVIZ Snapshot Grabber
version: 1.0.1
slug: ezviz_snapshots
description: Obtiene snapshots de c√°maras EZVIZ y los guarda en www/snapshots
arch:
  - aarch64
image: "ghcr.io/2513mendez/ezvizsnapshots"
startup: once
boot: manual
host_network: false

options:
  app_key: ""
  app_secret: ""
  token: ""
  camaras:
    - nombre: ""
      serial: ""

schema:
  app_key: str
  app_secret: str
  token: str
  camaras:
    - dict(nombre=str, serial=str)
